### ISSUE TITLE
Calibre plugin don't work with kupfer v325

### ISSUE THREAD

**Issue by a11g0rhythm** [KarolBedkowski/kupfer-contrib#2]
log from debug mode
`ERR [kupfer.core.plugins]: Could not import plugin 'calibre'
Traceback (most recent call last):
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 283, in _import_plugin_true
    plugin = _staged_import(name, _import_hook_true)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 302, in _staged_import
    return import_hook(_plugin_path(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 260, in _import_hook_true
    plugin = __import__(path, fromlist=fromlist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mariusz/.local/share/kupfer/plugins/calibre.py", line 445
    		print ext
    		^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
ERR [kupfer.core.plugins]: Could not import plugin 'calibre'
Traceback (most recent call last):
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 283, in _import_plugin_true
    plugin = _staged_import(name, _import_hook_true)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 302, in _staged_import
    return import_hook(_plugin_path(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/kupfer/kupfer/core/plugins.py", line 260, in _import_hook_true
    plugin = __import__(path, fromlist=fromlist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mariusz/.local/share/kupfer/plugins/calibre.py", line 445
    		print ext
    		^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
ERR [kupfer.core.plugins]: Could not import plugin 'calibre'
`

**Comment by KarolBedkowski** [comment]
This is old version (python2).
Use version from kupfer3 branch. Seems to work.

**Comment by a11g0rhythm** [comment]
I think calibre plugin is a "victim of refactoring code"
"cannot import name 'utils' from 'kupfer' (/usr/local/share/kupfer/kupfer/__init__.py)"

**Comment by KarolBedkowski** [comment]
This repo is unmaintained, but i pushed to master all old changes.
